In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [3]:
model = tf.keras.Sequential([tf.keras.layers.Dense(units = 1, input_shape = [1])])

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

In [7]:
x_data = np.array([1,2,3,4,5,6,7,8,9,10], dtype = float)
y_data = np.array([1.0, 1.5, 2.0, 2.5, 3.0, 3.5,4.0,4.5,5.0,5.5], dtype = float)

In [8]:
y_data /=100

In [13]:
model.fit(x_data, y_data, epochs = 1000)

Epoch 1/1000
10/10 [==============================] - 0s 658us/sample - loss: 2.5918e-04
Epoch 2/1000
10/10 [==============================] - 0s 200us/sample - loss: 2.5701e-04
Epoch 3/1000
10/10 [==============================] - 0s 202us/sample - loss: 2.5485e-04
Epoch 4/1000
10/10 [==============================] - 0s 219us/sample - loss: 2.5272e-04
Epoch 5/1000
10/10 [==============================] - 0s 199us/sample - loss: 2.5060e-04
Epoch 6/1000
10/10 [==============================] - 0s 181us/sample - loss: 2.4850e-04
Epoch 7/1000
10/10 [==============================] - 0s 444us/sample - loss: 2.4641e-04
Epoch 8/1000
10/10 [==============================] - 0s 199us/sample - loss: 2.4435e-04
Epoch 9/1000
10/10 [==============================] - 0s 200us/sample - loss: 2.4230e-04
Epoch 10/1000
10/10 [==============================] - 0s 212us/sample - loss: 2.4027e-04
Epoch 11/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.3826e-04
Epoch 12/1000
10/10

Epoch 93/1000
10/10 [==============================] - 0s 126us/sample - loss: 1.1948e-04
Epoch 94/1000
10/10 [==============================] - 0s 212us/sample - loss: 1.1848e-04
Epoch 95/1000
10/10 [==============================] - 0s 415us/sample - loss: 1.1749e-04
Epoch 96/1000
10/10 [==============================] - 0s 299us/sample - loss: 1.1650e-04
Epoch 97/1000
10/10 [==============================] - 0s 229us/sample - loss: 1.1553e-04
Epoch 98/1000
10/10 [==============================] - 0s 299us/sample - loss: 1.1456e-04
Epoch 99/1000
10/10 [==============================] - 0s 255us/sample - loss: 1.1360e-04
Epoch 100/1000
10/10 [==============================] - 0s 207us/sample - loss: 1.1265e-04
Epoch 101/1000
10/10 [==============================] - 0s 199us/sample - loss: 1.1170e-04
Epoch 102/1000
10/10 [==============================] - 0s 227us/sample - loss: 1.1077e-04
Epoch 103/1000
10/10 [==============================] - 0s 199us/sample - loss: 1.0984e-04
Epoch 

Epoch 184/1000
10/10 [==============================] - 0s 0s/sample - loss: 5.5549e-05
Epoch 185/1000
10/10 [==============================] - 0s 114us/sample - loss: 5.5083e-05
Epoch 186/1000
10/10 [==============================] - 0s 202us/sample - loss: 5.4621e-05
Epoch 187/1000
10/10 [==============================] - 0s 105us/sample - loss: 5.4163e-05
Epoch 188/1000
10/10 [==============================] - 0s 168us/sample - loss: 5.3708e-05
Epoch 189/1000
10/10 [==============================] - 0s 214us/sample - loss: 5.3259e-05
Epoch 190/1000
10/10 [==============================] - 0s 200us/sample - loss: 5.2812e-05
Epoch 191/1000
10/10 [==============================] - 0s 203us/sample - loss: 5.2370e-05
Epoch 192/1000
10/10 [==============================] - 0s 136us/sample - loss: 5.1932e-05
Epoch 193/1000
10/10 [==============================] - 0s 230us/sample - loss: 5.1496e-05
Epoch 194/1000
10/10 [==============================] - 0s 219us/sample - loss: 5.1064e-05
Ep

Epoch 275/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.5825e-05
Epoch 276/1000
10/10 [==============================] - 0s 232us/sample - loss: 2.5609e-05
Epoch 277/1000
10/10 [==============================] - 0s 199us/sample - loss: 2.5394e-05
Epoch 278/1000
10/10 [==============================] - 0s 286us/sample - loss: 2.5181e-05
Epoch 279/1000
10/10 [==============================] - 0s 249us/sample - loss: 2.4970e-05
Epoch 280/1000
10/10 [==============================] - 0s 376us/sample - loss: 2.4760e-05
Epoch 281/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.4553e-05
Epoch 282/1000
10/10 [==============================] - 0s 131us/sample - loss: 2.4347e-05
Epoch 283/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.4143e-05
Epoch 284/1000
10/10 [==============================] - 0s 237us/sample - loss: 2.3941e-05
Epoch 285/1000
10/10 [==============================] - 0s 231us/sample - loss: 2.3740e-05

Epoch 366/1000
10/10 [==============================] - 0s 290us/sample - loss: 1.2006e-05
Epoch 367/1000
10/10 [==============================] - 0s 326us/sample - loss: 1.1905e-05
Epoch 368/1000
10/10 [==============================] - 0s 259us/sample - loss: 1.1806e-05
Epoch 369/1000
10/10 [==============================] - 0s 401us/sample - loss: 1.1706e-05
Epoch 370/1000
10/10 [==============================] - 0s 200us/sample - loss: 1.1608e-05
Epoch 371/1000
10/10 [==============================] - 0s 179us/sample - loss: 1.1511e-05
Epoch 372/1000
10/10 [==============================] - 0s 204us/sample - loss: 1.1415e-05
Epoch 373/1000
10/10 [==============================] - 0s 125us/sample - loss: 1.1319e-05
Epoch 374/1000
10/10 [==============================] - 0s 100us/sample - loss: 1.1224e-05
Epoch 375/1000
10/10 [==============================] - 0s 200us/sample - loss: 1.1130e-05
Epoch 376/1000
10/10 [==============================] - 0s 0s/sample - loss: 1.1037e-05
Ep

Epoch 457/1000
10/10 [==============================] - 0s 200us/sample - loss: 5.5814e-06
Epoch 458/1000
10/10 [==============================] - 0s 170us/sample - loss: 5.5348e-06
Epoch 459/1000
10/10 [==============================] - 0s 199us/sample - loss: 5.4884e-06
Epoch 460/1000
10/10 [==============================] - 0s 261us/sample - loss: 5.4426e-06
Epoch 461/1000
10/10 [==============================] - 0s 0s/sample - loss: 5.3968e-06
Epoch 462/1000
10/10 [==============================] - 0s 192us/sample - loss: 5.3514e-06
Epoch 463/1000
10/10 [==============================] - 0s 267us/sample - loss: 5.3066e-06
Epoch 464/1000
10/10 [==============================] - 0s 299us/sample - loss: 5.2622e-06
Epoch 465/1000
10/10 [==============================] - 0s 100us/sample - loss: 5.2183e-06
Epoch 466/1000
10/10 [==============================] - 0s 100us/sample - loss: 5.1745e-06
Epoch 467/1000
10/10 [==============================] - 0s 244us/sample - loss: 5.1308e-06
Ep

Epoch 548/1000
10/10 [==============================] - 0s 200us/sample - loss: 2.5950e-06
Epoch 549/1000
10/10 [==============================] - 0s 233us/sample - loss: 2.5732e-06
Epoch 550/1000
10/10 [==============================] - 0s 174us/sample - loss: 2.5517e-06
Epoch 551/1000
10/10 [==============================] - 0s 103us/sample - loss: 2.5303e-06
Epoch 552/1000
10/10 [==============================] - 0s 211us/sample - loss: 2.5089e-06
Epoch 553/1000
10/10 [==============================] - 0s 0s/sample - loss: 2.4881e-06
Epoch 554/1000
10/10 [==============================] - 0s 281us/sample - loss: 2.4672e-06
Epoch 555/1000
10/10 [==============================] - 0s 194us/sample - loss: 2.4464e-06
Epoch 556/1000
10/10 [==============================] - 0s 216us/sample - loss: 2.4259e-06
Epoch 557/1000
10/10 [==============================] - 0s 268us/sample - loss: 2.4056e-06
Epoch 558/1000
10/10 [==============================] - 0s 203us/sample - loss: 2.3854e-06
Ep

Epoch 639/1000
10/10 [==============================] - 0s 201us/sample - loss: 1.2063e-06
Epoch 640/1000
10/10 [==============================] - 0s 299us/sample - loss: 1.1963e-06
Epoch 641/1000
10/10 [==============================] - 0s 332us/sample - loss: 1.1863e-06
Epoch 642/1000
10/10 [==============================] - 0s 401us/sample - loss: 1.1764e-06
Epoch 643/1000
10/10 [==============================] - 0s 414us/sample - loss: 1.1664e-06
Epoch 644/1000
10/10 [==============================] - 0s 318us/sample - loss: 1.1566e-06
Epoch 645/1000
10/10 [==============================] - 0s 201us/sample - loss: 1.1469e-06
Epoch 646/1000
10/10 [==============================] - 0s 168us/sample - loss: 1.1373e-06
Epoch 647/1000
10/10 [==============================] - 0s 142us/sample - loss: 1.1278e-06
Epoch 648/1000
10/10 [==============================] - 0s 199us/sample - loss: 1.1183e-06
Epoch 649/1000
10/10 [==============================] - 0s 103us/sample - loss: 1.1088e-06

Epoch 729/1000
10/10 [==============================] - 0s 124us/sample - loss: 5.6561e-07
Epoch 730/1000
10/10 [==============================] - 0s 284us/sample - loss: 5.6079e-07
Epoch 731/1000
10/10 [==============================] - 0s 258us/sample - loss: 5.5615e-07
Epoch 732/1000
10/10 [==============================] - 0s 100us/sample - loss: 5.5147e-07
Epoch 733/1000
10/10 [==============================] - 0s 100us/sample - loss: 5.4692e-07
Epoch 734/1000
10/10 [==============================] - 0s 279us/sample - loss: 5.4228e-07
Epoch 735/1000
10/10 [==============================] - 0s 188us/sample - loss: 5.3774e-07
Epoch 736/1000
10/10 [==============================] - 0s 100us/sample - loss: 5.3322e-07
Epoch 737/1000
10/10 [==============================] - 0s 200us/sample - loss: 5.2879e-07
Epoch 738/1000
10/10 [==============================] - 0s 274us/sample - loss: 5.2440e-07
Epoch 739/1000
10/10 [==============================] - 0s 200us/sample - loss: 5.1998e-07

10/10 [==============================] - 0s 0s/sample - loss: 2.6514e-07
Epoch 820/1000
10/10 [==============================] - 0s 153us/sample - loss: 2.6293e-07
Epoch 821/1000
10/10 [==============================] - 0s 222us/sample - loss: 2.6072e-07
Epoch 822/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.5862e-07
Epoch 823/1000
10/10 [==============================] - 0s 121us/sample - loss: 2.5637e-07
Epoch 824/1000
10/10 [==============================] - 0s 299us/sample - loss: 2.5422e-07
Epoch 825/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.5208e-07
Epoch 826/1000
10/10 [==============================] - 0s 100us/sample - loss: 2.5000e-07
Epoch 827/1000
10/10 [==============================] - 0s 299us/sample - loss: 2.4793e-07
Epoch 828/1000
10/10 [==============================] - 0s 0s/sample - loss: 2.4580e-07
Epoch 829/1000
10/10 [==============================] - 0s 131us/sample - loss: 2.4369e-07
Epoch 830/1000
10/10

Epoch 910/1000
10/10 [==============================] - 0s 433us/sample - loss: 1.2323e-07
Epoch 911/1000
10/10 [==============================] - 0s 273us/sample - loss: 1.2223e-07
Epoch 912/1000
10/10 [==============================] - 0s 229us/sample - loss: 1.2122e-07
Epoch 913/1000
10/10 [==============================] - 0s 189us/sample - loss: 1.2018e-07
Epoch 914/1000
10/10 [==============================] - 0s 200us/sample - loss: 1.1919e-07
Epoch 915/1000
10/10 [==============================] - 0s 100us/sample - loss: 1.1822e-07
Epoch 916/1000
10/10 [==============================] - 0s 300us/sample - loss: 1.1723e-07
Epoch 917/1000
10/10 [==============================] - 0s 100us/sample - loss: 1.1623e-07
Epoch 918/1000
10/10 [==============================] - 0s 507us/sample - loss: 1.1527e-07
Epoch 919/1000
10/10 [==============================] - 0s 155us/sample - loss: 1.1431e-07
Epoch 920/1000
10/10 [==============================] - 0s 658us/sample - loss: 1.1335e-07

In [14]:
model.predict([5])

array([[2.5001457]], dtype=float32)

In [15]:
model.predict([1])

array([[0.50044286]], dtype=float32)

In [16]:
model.predict([19])

array([[9.499105]], dtype=float32)